### PR TITLE
refactor: revamp project

### PR DESCRIPTION
**Pull request by damianopetrungaro**
BREAKING CHANGE: Container can't be initialized empty

### CODE REVIEW

**Comment by ElenaForester** [comment]
+1

**Comment by damianopetrungaro** [comment]
@ElenaForester  please use the Github's `review changes` button into `File changed` tab to approve the PR 😄

**Review by ElenaForester — DISMISSED** [review]
Ooops

**Comment by damianopetrungaro** [comment]
@ElenaForester  removed the .php_cs.cache file from the repo ;)

**Review by ElenaForester — DISMISSED** [review]

**Pull request merged**
